### ISSUE TITLE
Enforce POST HTTP method when creating a new data object using REST API

### ISSUE THREAD

**Issue by Rickos99** [SimonHotDog/D7024E---Mobile-and-Distributed-Computing-Systems#67]
In the lab requirements, it states that the route to create a new data object should be using the post HTTP method, `POST /objects`.

**Current behaviour** allows any HTTP method to be used.

**Expected behaviour** allows only the HTTP post method to be used.

**Comment by JunkZ** [comment]
Closed with #70
