### ISSUE TITLE
Enforce GET HTTP method when requesting a data object using REST API

### ISSUE THREAD

**Issue by Rickos99** [SimonHotDog/D7024E---Mobile-and-Distributed-Computing-Systems#68]
In the lab requirements, it states that the route used to request an existing data object should be using the get HTTP method, `GET /objects/{hash}`.

**Current behaviour** allows any HTTP method to be used.

**Expected behaviour** allows only the HTTP get method to be used.

**Comment by JunkZ** [comment]
Closed with #70
